---
- id: mypy
  name: mypy
  description: Run mypy static type checker
  entry: mypy
  language: python
  pass_filenames: false

- id: lint-markdown
  name: Lint Markdown files
  description: In place Markdown linter based on markdownlint
  entry: markdownlint -f
  types: [markdown]
  language: node
  additional_dependencies:
    - markdownlint
    - markdownlint-cli